version: '3.2'

services:
  jira-bot-ms:
    container_name: notification-app
    build:
      context: .
      dockerfile: ./build.dockerfile
    image: notification-app
    ports:
      - "8080:8080"
    environment:
      DB_HOST: jira-bot-db
      DB_PORT: 5432
      DB_LOGIN: postgres
      DB_PASSWORD: postgres
    networks:
      - jira-bot-net
networks:
  jira-bot-net:
    external: true
