version: '3.2'

services:
  notification-app:
    container_name: notification-app
    build:
      context: .
      dockerfile: ./build.dockerfile
    image: notification-app
    ports:
      - "8080:8080"
    environment:
      DB_HOST: jira-bot-db
      DB_PORT: 5432
      DB_LOGIN: postgres
      DB_PASSWORD: postgres
      PROXY_SERVICE_URL: "proxy-service:8083/tickets/jira"
      BOT_URL: "jira-bot-ms:8082"
    networks:
      - jira-bot-net
networks:
  jira-bot-net:
    external: true
