springdoc:
  swagger-ui:
    operationsSorter: "method"
feign:
  jira:
    url: "http://localhost:8081/tickets/jira"
  telegram-bot:
    url: "http://localhost:8082"
spring:
  datasource:
    driver-class-name: "org.postgresql.Driver"
    url: "jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/jira"
    username: "${DB_LOGIN:root}"
    password: "${DB_PASSWORD:root}"
  flyway:
    locations: "classpath:migration"
