CREATE TABLE IF NOT EXISTS JIRA.CHAT
(
    ID SERIAL PRIMARY KEY,
    TITLE VARCHAR(30),
    TELEGRAM_ID INTEGER UNIQUE NOT NULL,
    TYPE VARCHAR(15),
    STATUS VARCHAR(30),
    CREATED_DATE    TIMESTAMP NOT NULL,
    UPDATED_DATE    TIMESTAMP NOT NULL
)