CREATE TABLE IF NOT EXISTS JIRA.ISSUE
(
    ID SERIAL PRIMARY KEY,
    TITLE VARCHAR(100),
    CODE VARCHAR(15) UNIQUE NOT NULL,
    STATUS VARCHAR(30), -- field/resolution/name
    DESCRIPTION VARCHAR,  -- fields/description
    CREATED_DATE    TIMESTAMP NOT NULL,
    UPDATED_DATE    TIMESTAMP NOT NULL
)