create TABLE IF NOT EXISTS JIRA.ISSUE_CHAT
(
    ID        SERIAL PRIMARY KEY,
    CHAT_ID INTEGER NOT NULL REFERENCES JIRA.CHAT(ID),
    ISSUE_ID   INTEGER NOT NULL REFERENCES JIRA.ISSUE(ID),
    UNIQUE (ISSUE_ID, CHAT_ID)
);