create TABLE IF NOT EXISTS JIRA.JIRA_COMMENT
(
    ID SERIAL PRIMARY KEY,
    AUTHOR VARCHAR(100),
    DESCRIPTION VARCHAR,
    ISSUE_ID INTEGER,
    JIRA_ID INTEGER UNIQUE,
    CREATED_DATE    TIMESTAMP NOT NULL,
    UPDATED_DATE    TIMESTAMP NOT NULL
)